/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VideosRouteImport } from './routes/videos'
import { Route as ToolsRouteImport } from './routes/tools'
import { Route as NewsRouteImport } from './routes/news'
import { Route as HospitalsRouteImport } from './routes/hospitals'
import { Route as EncyclopediaRouteImport } from './routes/encyclopedia'
import { Route as DonorsRouteImport } from './routes/donors'
import { Route as DoctorsRouteImport } from './routes/doctors'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedAdminAdminsRouteImport } from './routes/_authenticated/admin.admins'
import { Route as AuthenticatedAdminResourceRouteImport } from './routes/_authenticated/admin.$resource'

const VideosRoute = VideosRouteImport.update({
  id: '/videos',
  path: '/videos',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsRoute = ToolsRouteImport.update({
  id: '/tools',
  path: '/tools',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsRoute = NewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => rootRouteImport,
} as any)
const HospitalsRoute = HospitalsRouteImport.update({
  id: '/hospitals',
  path: '/hospitals',
  getParentRoute: () => rootRouteImport,
} as any)
const EncyclopediaRoute = EncyclopediaRouteImport.update({
  id: '/encyclopedia',
  path: '/encyclopedia',
  getParentRoute: () => rootRouteImport,
} as any)
const DonorsRoute = DonorsRouteImport.update({
  id: '/donors',
  path: '/donors',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorsRoute = DoctorsRouteImport.update({
  id: '/doctors',
  path: '/doctors',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminAdminsRoute =
  AuthenticatedAdminAdminsRouteImport.update({
    id: '/admins',
    path: '/admins',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminResourceRoute =
  AuthenticatedAdminResourceRouteImport.update({
    id: '/$resource',
    path: '/$resource',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/doctors': typeof DoctorsRoute
  '/donors': typeof DonorsRoute
  '/encyclopedia': typeof EncyclopediaRoute
  '/hospitals': typeof HospitalsRoute
  '/news': typeof NewsRoute
  '/tools': typeof ToolsRoute
  '/videos': typeof VideosRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/admin/$resource': typeof AuthenticatedAdminResourceRoute
  '/admin/admins': typeof AuthenticatedAdminAdminsRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/doctors': typeof DoctorsRoute
  '/donors': typeof DonorsRoute
  '/encyclopedia': typeof EncyclopediaRoute
  '/hospitals': typeof HospitalsRoute
  '/news': typeof NewsRoute
  '/tools': typeof ToolsRoute
  '/videos': typeof VideosRoute
  '/admin/$resource': typeof AuthenticatedAdminResourceRoute
  '/admin/admins': typeof AuthenticatedAdminAdminsRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/auth': typeof AuthRoute
  '/doctors': typeof DoctorsRoute
  '/donors': typeof DonorsRoute
  '/encyclopedia': typeof EncyclopediaRoute
  '/hospitals': typeof HospitalsRoute
  '/news': typeof NewsRoute
  '/tools': typeof ToolsRoute
  '/videos': typeof VideosRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/admin/$resource': typeof AuthenticatedAdminResourceRoute
  '/_authenticated/admin/admins': typeof AuthenticatedAdminAdminsRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/doctors'
    | '/donors'
    | '/encyclopedia'
    | '/hospitals'
    | '/news'
    | '/tools'
    | '/videos'
    | '/admin'
    | '/admin/$resource'
    | '/admin/admins'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/doctors'
    | '/donors'
    | '/encyclopedia'
    | '/hospitals'
    | '/news'
    | '/tools'
    | '/videos'
    | '/admin/$resource'
    | '/admin/admins'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/doctors'
    | '/donors'
    | '/encyclopedia'
    | '/hospitals'
    | '/news'
    | '/tools'
    | '/videos'
    | '/_authenticated/admin'
    | '/_authenticated/admin/$resource'
    | '/_authenticated/admin/admins'
    | '/_authenticated/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthRoute: typeof AuthRoute
  DoctorsRoute: typeof DoctorsRoute
  DonorsRoute: typeof DonorsRoute
  EncyclopediaRoute: typeof EncyclopediaRoute
  HospitalsRoute: typeof HospitalsRoute
  NewsRoute: typeof NewsRoute
  ToolsRoute: typeof ToolsRoute
  VideosRoute: typeof VideosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/videos': {
      id: '/videos'
      path: '/videos'
      fullPath: '/videos'
      preLoaderRoute: typeof VideosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools': {
      id: '/tools'
      path: '/tools'
      fullPath: '/tools'
      preLoaderRoute: typeof ToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news': {
      id: '/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof NewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hospitals': {
      id: '/hospitals'
      path: '/hospitals'
      fullPath: '/hospitals'
      preLoaderRoute: typeof HospitalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/encyclopedia': {
      id: '/encyclopedia'
      path: '/encyclopedia'
      fullPath: '/encyclopedia'
      preLoaderRoute: typeof EncyclopediaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/donors': {
      id: '/donors'
      path: '/donors'
      fullPath: '/donors'
      preLoaderRoute: typeof DonorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctors': {
      id: '/doctors'
      path: '/doctors'
      fullPath: '/doctors'
      preLoaderRoute: typeof DoctorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/admins': {
      id: '/_authenticated/admin/admins'
      path: '/admins'
      fullPath: '/admin/admins'
      preLoaderRoute: typeof AuthenticatedAdminAdminsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/$resource': {
      id: '/_authenticated/admin/$resource'
      path: '/$resource'
      fullPath: '/admin/$resource'
      preLoaderRoute: typeof AuthenticatedAdminResourceRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminResourceRoute: typeof AuthenticatedAdminResourceRoute
  AuthenticatedAdminAdminsRoute: typeof AuthenticatedAdminAdminsRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminResourceRoute: AuthenticatedAdminResourceRoute,
  AuthenticatedAdminAdminsRoute: AuthenticatedAdminAdminsRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthRoute: AuthRoute,
  DoctorsRoute: DoctorsRoute,
  DonorsRoute: DonorsRoute,
  EncyclopediaRoute: EncyclopediaRoute,
  HospitalsRoute: HospitalsRoute,
  NewsRoute: NewsRoute,
  ToolsRoute: ToolsRoute,
  VideosRoute: VideosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
